name: Test faststream gen examples
on: [workflow_dispatch, pull_request, push]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Dependencies and library
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run pytest
        shell: bash
        run: |
          scripts/test.sh
          scripts/test.sh docs_src/tutorial/calculate-mean-app/tests/test_application.py
          scripts/test.sh docs_src/tutorial/retrieve-publish-crypto/tests/test_application.py
          scripts/test.sh docs_src/app_index_example/test.py

