name: Test faststream gen examples
on: [workflow_dispatch, pull_request, push]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install Dependencies and library
        shell: bash
        run: |
          set -ux
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      - name: Run pytest
        shell: bash
        run: bash scripts/test.sh

